#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
<<<<<<< HEAD
- {name: 'Humano',   url: 'proj-1'}
- {name: 'Contrôle',   url: 'proj-2'}
- {name: 'Design', url: 'proj-4'}
- {name: 'Production intéractive',  url: 'proj-5'}
=======
- {name: 'Project One',   url: 'proj-1'}
- {name: 'Project Two',   url: 'proj-2'}
- {name: 'Project Three', url: 'proj-3'}
- {name: 'Project Four',  url: 'proj-4'}
>>>>>>> parent of d8b6abf (ffafafsafas)

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/lenpaul'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.paul@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
